backend: apt
update_db: true
skip_if_no_internet: true

operations:
  - install:
      - firefox-esr
      - ffmpeg
      - libavcodec-extra
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - pipewire-audio
      - wireplumber
      - p7zip-full
      - unzip
      - unrar-free
      - fonts-noto-color-emoji
      - mesa-va-drivers
      - mesa-vulkan-drivers
  - remove:
      - live-boot
      - live-boot-doc
      - live-config
      - live-config-doc
      - live-config-systemd
      - live-tools
      - live-task-localisation
      - live-task-recommended
      - calamares-settings-debian
