---
modules-search:
  - local
  - /usr/lib/aarch64-linux-gnu/calamares/modules
  - /usr/lib/calamares/modules

instances:
  - id:       packages
    module:   packages
    config:   packages.conf
  - id:       quailinux-finish-install
    module:   shellprocess
    config:   quailinux-finish-install.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - services-systemd
      - packages
      - bootloader
      - quailinux-finish-install
      - umount
  - show:
      - finished

branding: quailinux
prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
quit-at-end: false
hide-back-and-next-during-exec: false
